//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace AnimalLibrary
{

    public abstract class Marine : Animal
    {



        /// <summary>
        /// An abstract method implementation for the marine subclasses
        /// </summary>
        /// <returns></returns>
        public abstract string MarineInfo();

        public abstract string SetDangerLevel();

    }
}
