//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace AnimalLibrary
{

    public abstract  class Reptile : Animal
    {


        //An abstract method for reptile subclasses
        public abstract string ReptileInfo();


        //An abstract method for the reptile subclasses
        public abstract string SetPoisonData();


    }

}